services:
  app:
    build: ./
    volumes:
      - ./:/var/www/
    ports:
      - 80:80
      - 443:443
    links:
      - database

  database:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: "!ChangeMe!"
    volumes:
      - data:/var/lib/postgresql/data:rw

volumes:
  data:
